### ISSUE TITLE
v1 Roadmap

### ISSUE THREAD

**Issue by himself65** [TexteaInc/y-socket.io#1]
1. [x] Allow everyone to join the yDoc, and everyone can make modifications. (like y-websocket basic usage)
2. [x] Support connects to persistence.
3. [x] Allow everyone to join the yDoc, but the yDoc owner could switch whether others can modify it. (permission control) https://github.com/TexteaInc/y-socket.io/pull/13
4. [ ] Allow invited users to see the yDoc(Authentication)
5. [ ] Support Viewer, Editor, Member, Owner...
